### ISSUE TITLE
429 Client Error

### ISSUE THREAD

**Issue by SolidPlague** [thags/lingqAnkiSync#30]
Hi folks,

The add-on has been working swimmingly for a couple of months on my end, but I'm now getting this error when trying to sync:

429 Client Error: Too Many Requests for url: https://www.lingq.com/api/v2/fi/cards/452013826/

I tried deleting the card referenced in the URL, but the error just happens again with a different card. I've tried to sync about five times in the past 12 hours.

Any thoughts?

**Comment by Austin-Chiappetta** [comment]
I'm also experiencing the exact same issue. I've been using this add-on for a few months with no problems, but now I also get the same error:
429 Client Error: Too Many Requests for url: https//www.lingq.com/api/v2/ru/cards/451904837/

**Comment by thags** [comment]
I started to look into this. It seems they started to rate limit requests. It's not that it's failing on that specific card, it's because the way their API is designed it needs to cycle through every card to do an update. After some amount of requests they then block you for a certain amount of time.

I can look into ways to resolve this. Unless they added a new method to their API the only way will probably be to add a delay to requests, which will make the syncing take longer.
